In [1]:
import numpy as np

# Basic Concepts

Linear algebra provides a way of compactly representing and operating on sets of linear
equations.
        
$$
\begin{array}{rcl}
x_1 + 2 x_2 &=& 5 \\
3 x_1 + 4 x_2 &=& 6\\
\end{array}
$$


This set of equations is compactly written as:
$$
    Ax = b
$$

where

$$A = \begin{bmatrix}
    1 & 2\\
    3 & 4
\end{bmatrix},\ \ \ \ b = \begin{bmatrix}
    5\\
    6
\end{bmatrix}$$

In [2]:
A = np.array([[1, 2], [3, 4]])
b = np.array([5, 6])

* If a matrix A has $m$ rows and $n$ columns, we say that A is an $m\times n$ matrix. If A has real valued entries, we say that $A \in \mathbb{R}^{mn}$

* A vector is a $m\times 1$ matrix.


The $j$th column of A is denoted by $A_{:, j}$

In [ ]:
# 0th column of A
print(A[:, 0])

[1 3]


The $i$th column of A is denoted by $A_{i, :}$

In [ ]:
# 0th row of A
print(A[0, :])

[1 2]


# Matrix Multiplication

## Vector-vector product

The inner product of vectors $x, y\in \mathbb{R}^n$ is given by:
$$
    x^T y = \sum_{i=1}^n x_i y_i
$$

The inner product is also called $dot\ product$, and sometimes denoted by $\langle x, y\rangle$

In [ ]:
x = np.array([1, 2])
y = np.array([3, 4])
z = x @ y
print(z)

11


# Matrix-vector product
Given an $m\times n$ matrix $A$, and a vector $x\in \mathbb{R}^n$, their product is a vector $y = Ax \in \mathbb{R^n}$:
$$
    y_i = A_i^T x
$$

In [ ]:
x = np.array([5, 6])
y = A @ x
print(y)

[17 39]


The product of the m×n matrix A and n×p matrix B is given an n×p matrix C, where
$$
C_{ij} = A_{i}^T B_{j}
$$

Properties:


*   Matrix multiplication is associative: $(AB)C = A(BC)$
*   Matrix multiplication is distributive: $A(B + C) = AB  + AC$
*   Matrix multiplication is, in general, not commutative: $AB\neq BA$, in general.



# Operations and properties

## Identity matrix
The identity matrix, denoted $I \in \mathbb{R}^{n\times n}$
, is a square matrix with ones on the diagonal and zeros everywhere else.

In [ ]:
q,  I = np.eye(5)
print(I)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


## Diagonal matrix
A diagonal matrix is a matrix where all non-diagonal elements are 0. This is typically
denoted D = diag($d_1, d_2, ..., d_n$)


In [ ]:
D = np.diag([1, 2, 3, 4])
print(D)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


## Transpose matrix

The transpose of a matrix results from "flipping" the rows and columns. Given an m×n matrix
A, its transpose, written $A^T \in \mathbb{R}^{n\times m}$, is the n × m matrix whose entries are given
by:

$$
    (A^T)_{ij} = A_{ji}
$$

In [ ]:
print(A.T)

[[1 3]
 [2 4]]


Properties:


*   $(A^T)^T = A$
*   $(A B)^T = B^T A^T$
*   $(A + B)^T = A^T + B^T$



## Matrix trace
The trace of an n×n square matrix  A, denoted tr(A) is the sum of diagonal elements in the matrix:
$$
tr(A) = \sum_{i=1}^n A_{ii}
$$

In [ ]:
print(np.trace(A))

5


Properties:


*   $tr(A) = tr(A^T)$
*   $tr(A + B) = tr(A) + tr(B)$
*   For any scalar $t\in \mathbb{R}$, $tr(t A) = t tr(A) $
*   For any matrices $A$, $B$ such that $AB$ is square, $tr(AB) = tr(BA)$
*   For any matrices $A$, $B$ and $C$ such that $ABC$ is square, $tr(ABC) = tr(BCA) = tr(CAB)$


## Norms of vectors

### $l_1$ norm
$$
    ||x||_{1} = \sum_{i=1}^n |x_i|
$$



In [ ]:
x = np.array([1, 2, 3, 4, 5])
np.linalg.norm(x, 1)

15.0

### $l_2$ norm
$$
    ||x||_{2} = \sqrt{\sum_{i=1}^n x_i^2}
$$



In [ ]:
np.linalg.norm(x, 2)

7.416198487095663

### $l_{\infty}$ norm
$$
    ||x||_{\infty} = \max_i{|x_i|}
$$



## Matrix inverse
The inverse of an $n \times n$ square matrix $A$ is denoted $A^{−1}$
, and is the unique matrix such that:
    $$
        A^{-1} A = I = A A^{-1}
    $$

In [ ]:
A_inverse = np.linalg.inv(A)
print(A_inverse)

[[-2.   1. ]
 [ 1.5 -0.5]]


In [ ]:
print(A @ A_inverse)

[[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]


## Quadratic Forms
Given a square matrix $A\in \mathbb{R}^{n\times n}$ and a vector $x\in \mathbb{R}^n$, the scalar value 

$$x^T A x$$

is called a quadratic form

In [ ]:
A = np.array([[1, 2], [3, 4]])
x = np.array([5, 6])
y = x @ A @ x
print(y)

319


# Gradient
Suppose that $f: \mathbb{R}^{m\times n}$ is a function that takes as input a matrix A of size m × n and
returns a real value. Then the gradient of f (with respect to A ∈ $\mathbb{R}$
m×n
) is the matrix of
partial derivatives, defined as:

$$
    \nabla_A f = \begin{bmatrix}
    \frac{\partial f}{\partial A_{11}} & \frac{\partial f}{\partial A_{12}}&...&\frac{\partial f}{\partial A_{1n}}\\
    \frac{\partial f}{\partial A_{21}} & \frac{\partial f}{\partial A_{22}}&...&\frac{\partial f}{\partial A_{2n}}\\
    ... & ...&...&...\\
    \frac{\partial f}{\partial A_{m1}} & \frac{\partial f}{\partial A_{m2}}&...&\frac{\partial f}{\partial A_{mn}}\\
\end{bmatrix}
$$



Note that the size of $\nabla_A f$ is always the same as the size of $A$. So if, in particular, A is
just a vector $x \in \mathbb{R}^n$

$$
    \nabla_x f(x) = \begin{bmatrix}
            \frac{\partial f}{\partial x_1}\\
            \frac{\partial f}{\partial x_2}\\
            \vdots\\
            \frac{\partial f}{\partial x_n}\\
        \end{bmatrix}
    $$

Properties:


1.   $\nabla_x (f(x) + g(x)) = \nabla_x f(x) + \nabla_x g(x)$
2.   $\nabla_x (\alpha f(x)) = \alpha \nabla_x f(x)$
3.   $\nabla_x (b^T x) = b$
4.   $\nabla_x (x^T A x) = (A + A^T) x$





In [ ]:
# Let's check property 4 with finite-differences
A = np.array([[1, 2], [3, 4]])
x = np.array([5, 6])

def f(x):
    return x @ A @ x

eps = 1e-5
df_dx0 = (f(x + [eps, 0]) - f(x)) / eps
df_dx1 = (f(x + [0, eps]) - f(x)) / eps
fd_gradient = [df_dx0, df_dx1]
print(fd_gradient)


[40.0000099944009, 73.00003999262117]


In [ ]:
analytical_gradient = (A + A.T) @ x
print(analytical_gradient)

[40 73]


Reference: Andrew Ng's CS 229 lecture notes:

http://cs229.stanford.edu/summer2019/cs229-linalg.pdf