In [9]:
import numpy as np
from numpy import exp as ℯ

discount = ℯ(-0.06)
S

# Regression at time 2
y = discount * np.array([0, 0.07, 0.18, 0.20, 0.09])
x = np.array([1.08, 1.07, .97, .77, .84])
X = np.column_stack([x**i for i in range(0, 3)])
Θ2 = np.linalg.lstsq(X, y, rcond=None)[0]
print(Θ2)

[-1.06998766  2.98341063 -1.81357618]


In [8]:
X

array([[1.    , 1.08  , 1.1664],
       [1.    , 1.07  , 1.1449],
       [1.    , 0.97  , 0.9409],
       [1.    , 0.77  , 0.5929],
       [1.    , 0.84  , 0.7056]])

In [2]:
def P2(S2):
    X = np.column_stack([S2**i for i in range(0, 3)])
    return X @ Θ2


S2 = np.array([1.08, 1.07, .97, .77, .84])

In [3]:
# For t = 1
r = 0.06
S1 = np.array([1.09, 0.93, .76, .92, .88])
X = np.column_stack([S1**i for i in range(0, 3)])

y = np.array([0., 0.13, .33, .26, 0.]) * np.exp(-r)
Θ1 = np.linalg.lstsq(X, y, rcond=None)[0]


def P1(S1):
    X = np.column_stack([np.ones_like(S1), S1, S1**2])
    return X @  Θ1


print(P1(S1))

[0.01348511 0.10874928 0.28606468 0.11700927 0.15276213]


In [4]:
d = np.exp(-r)
DFC = np.array([0, 0, 0.07 * d, .17 * d**3, 0., .34 * d, 0.18 * d, 0.22 * d])

In [5]:
P0 = np.mean(DFC)
print(P0)

0.11310315101789473
